version: 1.2.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- pwsh: nuget restore src/Rhyous.Collections.sln
configuration:
  Release
build:
  project: src/Rhyous.Collections.sln
  verbosity: minimal
test:
  categories:
    except:
    - slow
nuget:
  disable_publish_on_pr: true
artifacts:
  - path: '**\*.nupkg'
deploy:
- provider: NuGet
  on:
    branch: master
  api_key:
    secure: aBtwxNQUKVE+75XlHMIpG7dyc041X0T/svrpxRW0VfBH61cfv4dBZ1U8i9St3zR/